### ISSUE TITLE
errors on matplotlib

### ISSUE THREAD

**Issue by feefee20** [Roy-lab/grinch#3]
Hello, 

Thanks for the useful tool! 

While I've been learning your tool with the following commands with your shared 'tarball' data ( https://drive.google.com/file/d/1-iopSH7uI_Fra9wE6k6uGXeRXrwYQDoJ/view?usp=sharing), I've got some error messages in our system. It would be great if you help us to fix those issues.
 
---------------------------------------------------------------------------------
> python diamond.py diamond.ini

Drawing heatmap 1...
Drawing heatmap 2...

Traceback (most recent call last):
  File "~/grinch-master/visualization/diamond.py", line 88, in <module>
    main(sys.argv[1])
  File "~/grinch-master/visualization/diamond.py", line 84, in main
    gs.tight_layout(fig)
  File "~/.local/lib/python3.9/site-packages/matplotlib/gridspec.py", line 465, in tight_layout
    subplotspec_list = tight_layout.get_subplotspec_list(
  File "~/.local/lib/python3.9/site-packages/matplotlib/tight_layout.py", line 234, in get_subplotspec_list
    subplotspec = axes_or_locator.get_subplotspec()
  File "~/.local/lib/python3.9/site-packages/matplotlib/colorbar.py", line 283, in get_subplotspec
    ss = self._orig_locator.get_subplotspec()

AttributeError: 'AnchoredSizeLocator' object has no attribute 'get_subplotspec'

----------------------------------------------------------------------------------

Our environments are as follows:

- python=3.9.5
- matplotlib=3.5.2 
- pybigwig=not compatible with python 3.9

-----------------------------------------------------------------------------------

Thanks for your help!

**Comment by dyneofdata** [comment]
Hello, 

Thanks for bringing this to my attention. As you noted, the version of python you’re using (3.9) is not compatible with one of the dependencies (pyBigWig) + by default uses a version of matplotlib with a bug (https://github.com/matplotlib/matplotlib/issues/22576).
 
To get around this, please create a conda environment by specifying the versions of each dependency (this command might take a while).
 
`conda create --name grinch_env python=3.7.12 numpy=1.20.3 pandas=1.3.5 matplotlib=3.3.3 seaborn=0.12.1 pyBigWig=0.3.18 -c conda-forge -c bioconda`
 
Then activate the environment and run all scripts within that environment.
 
```
conda activate grinch_env
python diamond.py diamond.ini
python pyramid.py pyramid.ini
conda deactivate #to go back to your base python
```
I updated the github documentation with the version information.
 
Erika

**Comment by dyneofdata** [comment]
Verified with the user that the solution worked, closing!
